workflows:
  maui_build:
    name: .NET MAUI Build (.NET 8.0)
    instance_type: mac_mini_m1

    environment:
      vars:
        CONFIGURATION: Release
      xcode: 15.4

    scripts:
      # 1️⃣ Cài .NET 8 SDK qua Homebrew (chắc chắn hoạt động trên mac_mini_m1)
      - name: Install .NET 8 SDK
        script: |
          echo "Installing .NET 8 SDK..."
          brew update
          brew install --cask dotnet-sdk
          echo "Adding .NET to PATH..."
          export PATH="/usr/local/share/dotnet:$PATH"
          ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/dotnet || true
          dotnet --info

      # 2️⃣ Cài workloads MAUI
      - name: Install MAUI workloads
        script: |
          export PATH="/usr/local/share/dotnet:$PATH"
          dotnet workload install maui android ios maccatalyst --skip-sign-check --ignore-failed-sources

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        script: |
          export PATH="/usr/local/share/dotnet:$PATH"
          dotnet workload restore
          dotnet restore

      # 4️⃣ Build Android (.apk)
      - name: Build Android
        script: |
          export PATH="/usr/local/share/dotnet:$PATH"
          dotnet publish -f net8.0-android -c $CONFIGURATION -o build/android

      # 5️⃣ Build iOS (.ipa)
      - name: Build iOS
        script: |
          export PATH="/usr/local/share/dotnet:$PATH"
          dotnet publish -f net8.0-ios -c $CONFIGURATION -o build/ios /p:BuildIpa=true

    artifacts:
      - build/android/**/*.apk
      - build/ios/**/*.ipa

    cache:
      cache_paths:
        - ~/.nuget/packages
        - ~/.dotnet
