workflows:
  maui_build:
    name: .NET MAUI iOS + Android (.NET 8)
    instance_type: mac_mini_m1

    environment:
      vars:
        CONFIGURATION: Release
        DOTNET_ROOT: /Users/builder/dotnet8
        DOTNET_MULTILEVEL_LOOKUP: 0
      xcode: 15.4

    scripts:
      # Cài .NET 8 SDK (user-local, không ảnh hưởng .NET 9)
      - name: Install .NET 8 SDK
        script: |
          echo "Installing .NET 8 SDK locally..."
          mkdir -p $HOME/dotnet8
          curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 8.0 --install-dir $HOME/dotnet8
          export PATH="$HOME/dotnet8:$PATH"
          dotnet --info

      # Cài workloads MAUI cho .NET 8 (không cần sudo)
      - name: Install MAUI workloads
        script: |
          export PATH="$HOME/dotnet8:$PATH"
          export DOTNET_CLI_HOME="$HOME/.dotnet"
          export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
          dotnet workload install maui android ios maccatalyst --ignore-failed-sources
          dotnet workload list

      # Restore project dependencies
      - name: Restore dependencies
        script: |
          export PATH="$HOME/dotnet8:$PATH"
          dotnet restore

      # Cài Android SDK Platform 34
      - name: Ensure Android SDK Platform 34 exists
        script: |
          echo "Checking sdkmanager location..."
          export PATH=$PATH:/usr/local/share/android-sdk/cmdline-tools/latest/bin:/usr/local/share/android-sdk/tools/bin:/opt/homebrew/share/android-sdk/cmdline-tools/latest/bin
          which sdkmanager || true

          echo "Accepting Android licenses..."
          yes | sdkmanager --licenses || true

          echo "Installing Android SDK Platform 34..."
          yes | sdkmanager --install "platforms;android-34" "platform-tools" "build-tools;34.0.0"

          echo "Listing installed platforms..."
          ls -la /usr/local/share/android-sdk/platforms || true

      # Build Android APK
      - name: Build Android
        script: |
          export PATH="$HOME/dotnet8:$PATH"
          dotnet publish -f net8.0-android -c $CONFIGURATION -o build/android

      # Build iOS IPA
      - name: Build iOS IPA
        script: |
          export PATH="$HOME/dotnet8:$PATH"
          dotnet publish -f net8.0-ios -c $CONFIGURATION -o build/ios /p:BuildIpa=true

    artifacts:
      - build/android/**/*.apk
      - build/ios/**/*.ipa

    cache:
      cache_paths:
        - ~/.nuget/packages
        - ~/.dotnet
