workflows:
  maui_build:
    name: .NET MAUI Build (.NET 8.0)
    instance_type: mac_mini_m1

    environment:
      vars:
        CONFIGURATION: Release
        DOTNET_ROOT: /usr/local/share/dotnet/x64
      xcode: 15.4

    scripts:
      # 1️⃣ Chọn đúng version .NET 8
      - name: Use .NET 8 SDK
        script: |
          echo "Setting .NET 8 SDK manually..."
          export PATH="/usr/local/share/dotnet/x64:$PATH"
          dotnet --list-sdks
          echo "Using .NET SDK version:"
          dotnet --version

      # 2️⃣ Cài workload MAUI cục bộ
      - name: Install MAUI workloads
        script: |
          echo "Installing MAUI workloads for .NET 8..."
          export PATH="/usr/local/share/dotnet/x64:$PATH"
          dotnet workload install maui android ios maccatalyst --skip-sign-check --ignore-failed-sources

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        script: |
          export PATH="/usr/local/share/dotnet/x64:$PATH"
          dotnet workload restore
          dotnet restore

      # 4️⃣ Build Android (.apk)
      - name: Build Android
        script: |
          export PATH="/usr/local/share/dotnet/x64:$PATH"
          dotnet publish -f net8.0-android -c $CONFIGURATION -o build/android

      # 5️⃣ Build iOS (.ipa)
      - name: Build iOS
        script: |
          export PATH="/usr/local/share/dotnet/x64:$PATH"
          dotnet publish -f net8.0-ios -c $CONFIGURATION -o build/ios /p:BuildIpa=true

    artifacts:
      - build/android/**/*.apk
      - build/ios/**/*.ipa

    cache:
      cache_paths:
        - ~/.nuget/packages
        - ~/.dotnet
