workflows:
  maui_build:
    name: .NET MAUI Build (.NET 8)
    instance_type: mac_mini_m1

    environment:
      vars:
        DOTNET_VERSION: 8.0.100
        CONFIGURATION: Release

    scripts:
      - name: Use .NET 8 SDK
        script: |
          export PATH="$PATH:$HOME/.dotnet"
          echo "Using .NET SDK version $DOTNET_VERSION"
          dotnet --version || (
            echo "Installing .NET SDK $DOTNET_VERSION" &&
            brew install --cask dotnet-sdk
          )
          dotnet --info

      - name: Restore dependencies
        script: |
          echo "Restoring .NET workloads and NuGet packages..."
          dotnet workload restore
          dotnet restore

      - name: Build Android
        script: |
          dotnet publish -f net8.0-android -c $CONFIGURATION -o build/android

      - name: Build iOS
        script: |
          dotnet publish -f net8.0-ios -c $CONFIGURATION -o build/ios /p:BuildIpa=true

    artifacts:
      - build/android/**/*.apk
      - build/ios/**/*.ipa

    cache:
      cache_paths:
        - ~/.nuget/packages
        - ~/.dotnet
