workflows:
  build-ios-simulator:
    name: Build iOS Simulator App (.app for BrowserStack)
    environment:
      vars:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        CONFIGURATION: Release
        OUTPUT_DIR: build_output
      xcode: latest
      groups:
        - dotnet
    scripts:
      - name: Install .NET 8 SDK
        script: |
          brew install --cask dotnet-sdk
          dotnet --version

      - name: Install MAUI workloads
        script: |
          dotnet workload install maui-ios --ignore-failed-sources

      - name: Restore dependencies
        script: |
          dotnet restore SF_Demo.sln

      - name: Build iOS Simulator App
        script: |
          dotnet publish SF_Demo/SF_Demo.csproj \
            -f net8.0-ios \
            -c $CONFIGURATION \
            -p:BuildIpa=false \
            -p:RuntimeIdentifier=iossimulator-arm64 \
            -o $OUTPUT_DIR

      - name: Package .app for upload
        script: |
          cd $OUTPUT_DIR
          APP_NAME=$(ls -d *.app | head -n 1)
          zip -r "${APP_NAME%.app}.zip" "$APP_NAME"
          echo "App packaged as ${APP_NAME%.app}.zip"

    artifacts:
      - $OUTPUT_DIR/*.zip

    publishing:
      email:
        recipients:
          - your_email@example.com
