workflows:
  maui_build:
    name: .NET MAUI Build (Android + iOS)
    instance_type: mac_mini_m1

    environment:
      vars:
        DOTNET_VERSION: 9.0.306
        CONFIGURATION: Release

    scripts:
      - name: Install .NET SDK
        script: |
          export PATH="$PATH:$HOME/.dotnet"
          dotnet --version
          dotnet --info

      # ✅ Thay vì install, chỉ restore (an toàn, không cần quyền sudo)
      - name: Restore dependencies
        script: |
          dotnet workload restore
          dotnet restore

      - name: Build Android
        script: |
          dotnet publish -f net9.0-android -c $CONFIGURATION -o build/android

      - name: Build iOS
        script: |
          dotnet publish -f net9.0-ios -c $CONFIGURATION -o build/ios /p:BuildIpa=true

    artifacts:
      - build/android/**/*.apk
      - build/ios/**/*.ipa
